version: '3'

services:  
  infosoft-server:
    container_name: infosoft-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/data/cert.pfx
    volumes:
      - ./:/data